#!/bin/bash
#================================================
#================================================
#   Write for  Gnu-Linux O.S                    =
#   Author  : Cristian Pozzessere     = ilnanny =
#   D.A.Page   : http://lnanny.deviantart.com   =
#   Git Hub Page : https://github.com/ilnanny   =
#================================================
#================================================
#inserisci il file nella cartella ~.config/xfce/
#dalle impostazioni di tastiera ,assegna una nuova scorciatoia es. ctrl+canc
xkill -id "`xprop -root -notype | sed -n '/^_NET_ACTIVE_WINDOW/ s/^.*# *\|\,.*$//g p'`"
